name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  awesome-lint:
    name: awesome-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - run: npx awesome-lint https://github.com/Shashank-Tripathi-07/awesome-ml-systems-engineering

  link-check:
    name: link-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check links
        uses: lycheeverse/lychee-action@v1
        with:
          args: >
            --verbose
            --no-progress
            --exclude-mail
            --exclude "reddit.com"
            --exclude "linkedin.com"
            --exclude "twitter.com"
            --exclude "x.com"
            README.md
          fail: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
